
DESCRIBE RESERVATION;
DESCRIBE REPRESENTATION;
DESCRIBE COURS;
DESCRIBE PONEY;
DESCRIBE RACE;
DESCRIBE PAYER;
DESCRIBE COTISATION;
DESCRIBE FACTURE_SOLDE;
DESCRIBE DISPONIBILITE;
DESCRIBE OBTENTION;
DESCRIBE NIVEAU;
DESCRIBE MONITEUR;
DESCRIBE CLIENT;
DESCRIBE PERSONNE;